Update terraform-apply-resource.yaml

diff --git a/.github/workflows/terraform-apply-resource.yaml b/.github/workflows/terraform-apply-resource.yaml
--- a/.github/workflows/terraform-apply-resource.yaml
+++ b/.github/workflows/terraform-apply-resource.yaml
@@ -39,28 +39,38 @@ jobs:
       - name: Download Terraform Plan Artifact
         run: |
           mkdir terraform-artifact
-          curl -sSL -o terraform-artifact/terraform-artifact.zip -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/tfport-r_CQx19Ix1Lawf3IW8/zip"
-
-          # curl \
-          #   -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
-          #   -H "Accept: application/vnd.github.v3.raw" \
-          #   -o terraform-artifact/terraform-artifact.zip \
-          #   -L "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/tfport-r_CQx19Ix1Lawf3IW8/zip"
+          #curl -sSL -o terraform-artifact/terraform-artifact.zip -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/tfport-r_CQx19Ix1Lawf3IW8/zip"
+          
+          mkdir terraform-artifact
+          cd terraform-artifact
+          artifact_url=$(curl -sSL -I -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/tfport-r_CQx19Ix1Lawf3IW8/zip" | grep -i "location:" | awk '{print $2}' | tr -d '\r')
+          curl -sSL -o terraform-artifact.zip "$artifact_url"
+          if [ $? -ne 0 ]; then
+            echo "Failed to download artifact. Exiting."
+            exit 1
+          fi
+          unzip -qq terraform-artifact.zip
+          if [ $? -ne 0 ]; then
+            echo "Failed to extract artifact. Exiting."
+            exit 1
+          fi
 
       # List contents of the app directory
       - name: List all Directory Contents
-        run: ls -la 
-        
-      # List contents of the app directory
-      - name: List app Directory Contents
-        run: ls -la terraform-artifact
-        
-     # Unzip the downloaded zip file
-      - name: Unzip Terraform Plan File
         run: |
           pwd
-          cd terraform-artifact
-          unzip terraform-artifact.zip
+          ls -la 
+        
+      # List contents of the app directory
+      # - name: List app Directory Contents
+      #   run: ls -la terraform-artifact
+        
+     # # Unzip the downloaded zip file
+     #  - name: Unzip Terraform Plan File
+     #    run: |
+     #      pwd
+     #      cd terraform-artifact
+     #      unzip terraform-artifact.zip
           
       # List contents of the app directory
       - name: List app Directory Contents
